from datetime import datetime
from pathlib import Path
import json


def save_report(
    startup_idea: str,
    competitors: dict,
    pain_points: dict,
    founder_fit: dict,
    opportunity_score: dict,
) -> str:
    Path("reports").mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"reports/{timestamp}.md"

    # ── Format Competitors (categorized) ──
    comp_section = ""
    if isinstance(competitors, dict):
        categories = [
            ("🔴 Direct Competitors", "direct"),
            ("🟡 Indirect Competitors", "indirect"),
            ("🟠 Adjacent Threats", "adjacent"),
            ("🔵 Potential Entrants", "potential"),
        ]
        for label, key in categories:
            items = competitors.get(key, [])
            if items:
                comp_section += f"\n**{label}:**\n"
                comp_section += "\n".join(f"- {c}" for c in items)
            else:
                comp_section += f"\n**{label}:**\n- None found"
    else:
        comp_section = str(competitors)

    # ── Format Pain Points ──
    pain_section = ""
    if isinstance(pain_points, dict):
        pain_labels = {
            "pain_points": "😣 Customer Pain Points",
            "problems": "⚠️ Problems with Existing Solutions",
            "market_gaps": "💡 Market Gaps",
        }
        for key, label in pain_labels.items():
            items = pain_points.get(key, [])
            if items:
                pain_section += f"\n**{label}:**\n"
                pain_section += "\n".join(f"- {p}" for p in items)
            else:
                pain_section += f"\n**{label}:**\n- None identified"

    # ── Format Founder Fit ──
    ff = founder_fit if isinstance(founder_fit, dict) else {}
    fit_section = f"""
**Technical Fit:** {ff.get('technical_fit', 'N/A')}/100
**Domain Fit:** {ff.get('domain_fit', 'N/A')}/100
**Execution Speed:** {ff.get('execution_speed', 'N/A')}/100
**Market Understanding:** {ff.get('market_understanding', 'N/A')}/100

**Key Strengths:**
{chr(10).join(f'- {s}' for s in ff.get('key_strengths', [])) if ff.get('key_strengths') else '- N/A'}

**Key Weaknesses:**
{chr(10).join(f'- {w}' for w in ff.get('key_weaknesses', [])) if ff.get('key_weaknesses') else '- N/A'}

**Missing Skills:**
{chr(10).join(f'- {m}' for m in ff.get('missing_skills', [])) if ff.get('missing_skills') else '- None identified'}

**Co-Founder Recommendation:** {ff.get('co_founder_recommendation', 'N/A')}

**Solo Viability:** {ff.get('solo_viability', 'N/A')} — {ff.get('solo_viability_reason', '')}

**Summary:** {ff.get('summary', 'N/A')}
"""

    # ── Format Opportunity Score ──
    os_data = opportunity_score if isinstance(opportunity_score, dict) else {}
    score_section = f"""
**Market Pain Score:** {os_data.get('market_pain_score', 'N/A')}/100
**Competition Score:** {os_data.get('competition_score', 'N/A')}/100
**Founder Fit Score:** {os_data.get('founder_fit', 'N/A')}/100
**Timing Score:** {os_data.get('timing', 'N/A')}/100
**Overall Score:** {os_data.get('overall_score', 'N/A')}/100
**Verdict:** {os_data.get('verdict', 'N/A')}
**Reasoning:** {os_data.get('reasoning', 'N/A')}
"""

    # ── Build Full Report ──
    report = f"""# 🚀 Startup Analysis Report

**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Idea:** {startup_idea}

---

## 🔍 Competitor Analysis
{comp_section}

---

## 📊 Pain Point Analysis
{pain_section}

---

## 👤 Founder Fit Analysis
{fit_section}

---

## 📈 Opportunity Score
{score_section}

---

*Report generated by Founder Intelligence Agent*
"""

    with open(filename, "w", encoding="utf-8") as f:
        f.write(report)

    return filename
